#define NETWORK_SSID "SUPER_PRIVATE_NETWORK_NAME"
#define NETWORK_PASSWD "SUPER_SECURE_NETWORK_PASSWORD"

#define APP_ID "YOUR_APP_ID"
#define APP_KEY "YOUR_API_KEY"

#define ZIP_STRING "us.98101"
#define CITY_NAME "Seattle"
